/*----------------------------------------------------------------------------
 *
 * remove_palindromic_subsequences.c
 *   Given a string `s` consisting only of letters `'a'` and `'b'`. In a
 *   single step you can remove one palindromic subsequence from `s`.
 *
 *   Return the minimum number of steps to make the given string empty.
 *
 *   A string is a subsequence of a given string, if it is generated by
 *   deleting some characters of a given string without changing its order.
 *
 *   A string is called palindrome if is one that reads the same backward
 *   as well as forward.
 *
 *----------------------------------------------------------------------------
 */
static bool
isPalindrome(char *s, size_t len)
{
    char *p = s + len - 1;

    while (s < p && *s == *p) {
        s++;
        p--;
    }

    return s >= p;
}

int
removePalindromeSub(char * s)
{
    size_t len = strlen(s);

    if (len == 0) {
        return 0;
    } else if (isPalindrome(s, len)) {
        return 1;
    }

    return 2;
}